// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gasbygas.lb.dbcontex.tables.Models
{
    public partial class certificatevalidation
    {
        public int CertificateValidationID { get; set; }
        public int UserID { get; set; }
        public int CustomerID { get; set; }
        public string CertificateFileNumber { get; set; }
        public string CertificateStatus { get; set; }
        public string ValidationStatus { get; set; }
        public string ValidationDate { get; set; }

        public virtual customer Customer { get; set; }
        public virtual user User { get; set; }
    }
}