// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace gasbygas.lb.dbcontex.tables.Models
{
    public partial class gasbygasContext : DbContext
    {
        public gasbygasContext()
        {
        }

        public gasbygasContext(DbContextOptions<gasbygasContext> options)
            : base(options)
        {
        }

        public virtual DbSet<customer> customers { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.UseCollation("utf8mb4_0900_ai_ci")
                .HasCharSet("utf8mb4");

            modelBuilder.Entity<customer>(entity =>
            {
                entity.ToTable("customer");

                entity.HasComment("All End Customer Details");

                entity.HasIndex(e => e.CustomerId, "CUSTOMER_ID_UNIQUE")
                    .IsUnique();

                entity.Property(e => e.Address).HasMaxLength(200);

                entity.Property(e => e.ContactNumber).HasMaxLength(45);

                entity.Property(e => e.CustomerType).HasMaxLength(1);

                entity.Property(e => e.Email).HasMaxLength(45);

                entity.Property(e => e.FirstName).HasMaxLength(45);

                entity.Property(e => e.LastName).HasMaxLength(45);

                entity.Property(e => e.NIC).HasMaxLength(45);

                entity.Property(e => e.Password).HasMaxLength(45);

                entity.Property(e => e.RegistrationDate).HasMaxLength(45);

                entity.Property(e => e.Status).HasMaxLength(1);

                entity.Property(e => e.UpdatedBy).HasMaxLength(45);

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

                entity.Property(e => e.UserName).HasMaxLength(45);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}