// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gasbygas.lb.dbcontex.tables.Models
{
    public partial class gasrequest
    {
        public gasrequest()
        {
            relocatedNewRequests = new HashSet<relocated>();
            relocatedOldRequests = new HashSet<relocated>();
            tokens = new HashSet<token>();
        }

        public int RequestID { get; set; }
        public int CustomerID { get; set; }
        public int UserID { get; set; }
        public int OutletID { get; set; }
        public string RequestCategory { get; set; }
        public int GasQTY { get; set; }
        public string GasType { get; set; }
        public DateTime GasNeedDate { get; set; }
        public DateTime? RequestDate { get; set; }
        public string RequestStatus { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual customer Customer { get; set; }
        public virtual outlet Outlet { get; set; }
        public virtual user User { get; set; }
        public virtual ICollection<relocated> relocatedNewRequests { get; set; }
        public virtual ICollection<relocated> relocatedOldRequests { get; set; }
        public virtual ICollection<token> tokens { get; set; }
    }
}