// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gasbygas.lb.dbcontex.tables.Models
{
    public partial class notification
    {
        public int NotificationID { get; set; }
        public int TokenID { get; set; }
        public int UserID { get; set; }
        public int CustomerID { get; set; }
        public string NotificationType { get; set; }
        public string Message { get; set; }
        public DateTime? DateSent { get; set; }
        public string NotificationStatus { get; set; }
        public string Reference { get; set; }

        public virtual customer Customer { get; set; }
        public virtual token Token { get; set; }
        public virtual user User { get; set; }
    }
}