// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gasbygas.lb.dbcontex.tables.Models
{
    public partial class outlet
    {
        public outlet()
        {
            gasrequests = new HashSet<gasrequest>();
            outletstocks = new HashSet<outletstock>();
            users = new HashSet<user>();
        }

        public int OutletID { get; set; }
        public string OutletName { get; set; }
        public string ContactDetails { get; set; }
        public string Location { get; set; }
        public string District { get; set; }

        public virtual ICollection<gasrequest> gasrequests { get; set; }
        public virtual ICollection<outletstock> outletstocks { get; set; }
        public virtual ICollection<user> users { get; set; }
    }
}