// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gasbygas.lb.dbcontex.tables.Models
{
    public partial class outletstock
    {
        public int OutletStockID { get; set; }
        public string GasType { get; set; }
        public int? EmptyGaSQTY { get; set; }
        public int? GasStockLevel { get; set; }
        public int? ReceivingQTY { get; set; }
        public DateTime? ReceivingDate { get; set; }
        public int? EmptyReturnQTY { get; set; }
    }
}