// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gasbygas.lb.dbcontex.tables.Models
{
    public partial class payment
    {
        public int PaymentID { get; set; }
        public int TokenID { get; set; }
        public string Status { get; set; }
        public string Bank { get; set; }
        public string PaymentType { get; set; }
        public string AccountNumber { get; set; }
        public decimal? Price { get; set; }
        public string Branch { get; set; }

        public virtual token Token { get; set; }
    }
}