// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gasbygas.lb.dbcontex.tables.Models
{
    public partial class relocated
    {
        public int RelocateID { get; set; }
        public int OldTokenID { get; set; }
        public int? NewTokenID { get; set; }
        public int OldRequestID { get; set; }
        public int? NewRequestID { get; set; }
        public DateTime RelocationDate { get; set; }
        public string RelocationStatus { get; set; }

        public virtual gasrequest OldRequest { get; set; }
        public virtual token OldToken { get; set; }
    }
}