// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gasbygas.lb.dbcontex.tables.Models
{
    public partial class token
    {
        public token()
        {
            notifications = new HashSet<notification>();
            payments = new HashSet<payment>();
            relocateds = new HashSet<relocated>();
        }

        public int TokenID { get; set; }
        public int RequestID { get; set; }
        public int? ParentTokenID { get; set; }
        public int UserID { get; set; }
        public int GasQTY { get; set; }
        public string GasType { get; set; }
        public double UnitPrice { get; set; }
        public double Total { get; set; }
        public DateTime PurchaseStartDate { get; set; }
        public DateTime PurchaseEndDate { get; set; }
        public DateTime? PickupDate { get; set; }
        public DateTime TokenReturnDate { get; set; }
        public string TokenStatus { get; set; }
        public int? ReturnEmptyQTY { get; set; }
        public string EmptyGasStatus { get; set; }
        public string ReallocatedBy { get; set; }
        public string TokenNumber { get; set; }

        public virtual gasrequest Request { get; set; }
        public virtual user User { get; set; }
        public virtual ICollection<notification> notifications { get; set; }
        public virtual ICollection<payment> payments { get; set; }
        public virtual ICollection<relocated> relocateds { get; set; }
    }
}