// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gasbygas.lb.dbcontex.tables.Models
{
    public partial class user
    {
        public user()
        {
            certificatevalidations = new HashSet<certificatevalidation>();
            deliveries = new HashSet<delivery>();
            gasrequests = new HashSet<gasrequest>();
            gasstocks = new HashSet<gasstock>();
            notifications = new HashSet<notification>();
            tokens = new HashSet<token>();
        }

        public int UserID { get; set; }
        public int? OutletID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
        public string UserRole { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? LastLoginDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }

        public virtual outlet Outlet { get; set; }
        public virtual ICollection<certificatevalidation> certificatevalidations { get; set; }
        public virtual ICollection<delivery> deliveries { get; set; }
        public virtual ICollection<gasrequest> gasrequests { get; set; }
        public virtual ICollection<gasstock> gasstocks { get; set; }
        public virtual ICollection<notification> notifications { get; set; }
        public virtual ICollection<token> tokens { get; set; }
    }
}